a=int(input("enter integer:"))
b=float(input("enter float:"))
c=input("enter the string")
print("integer to float:",float(a))
print("integer to string:",str(a))
print("float to integer:",int(b))
print("float to string:",float(b))
print("string to integer:",str(c))
print("string to float:",str(c))